=== thatline/thatline.github.io/test/lines.schema.json
{
    "$id": "https://thatline.github.io/test/lines.schema.json",
    "$schema": "http://json-schema.org/draft-03/schema",
    "description": "Lines for thatline.github.io",
    "type": "array",
    "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
            "artist": {
                "type": "string",
                "required": true
            },
            "genius_link": {
                "type": "string",
                "required": true
            },
            "line": {
                "type": "string",
                "required": true
            },
            "song": {
                "type": "string",
                "required": true
            }
        }
    }
}

=== thatline/thatline.github.io/src/data/lines.json
[
    {
        "artist": "Estelle",
        "song": "American Boy ft. Kanye West",
        "line": "Look at this pea coat, tell me he’s broke",
        "genius_link": "https://genius.com/91238"
    },
    {
        "artist": "Tinie Tempah",
        "song": "Pass Out",
        "line": "Now I drive past the bus I used to run for",
        "genius_link": "https://genius.com/Tinie-tempah-pass-out-lyrics"
    },
    {
        "artist": "Kanye West",
        "song": "Junya",
        "line": "I won with the bucks, boy, let me Giannis",
        "genius_link": "https://genius.com/23571738"
    },
    {
        "artist": "The Weeknd",
        "song": "Sidewalks ft. Kendrick Lamar",
        "line": "Grew up with no father so nobody ever son me",
        "genius_link": "https://genius.com/10897433"
    },
    {
        "artist": "The Weeknd",
        "song": "Tell Your Friends",
        "line": "Cruise through the west–end in my new Benz, I’m just tryna live life through a new lens",
        "genius_link": "https://genius.com/7659455"
    },
    {
        "artist": "Lupe Fiasco",
        "song": "The Show Goes On",
        "line": "I was once that little boy, terrified of the world, now I’m on a world tour",
        "genius_link": "https://genius.com/15947465/Lupe-fiasco-the-show-goes-on/Yeah-yeah-the-world-is-yours-i-was-once-that-little-boy-terrified-of-the-world-now-im-on-a-world-tour"
    },
    {
        "artist": "Consequence",
        "song": "Grammy Family ft. Kanye West, DJ Khaled, John Legend",
        "line": "Hi haters I’m back off hiatus, I feel just like you, I mean even I hate us",
        "genius_link": "https://genius.com/Consequence-grammy-family-lyrics"
    },
    {
        "artist": "Jay-Z",
        "song": "U Don’t Know",
        "line": "Put me anywhere on God’s green earth,  I’ll triple my worth",
        "genius_link": "https://genius.com/381141"
    },
    {
        "artist": "Wu-Tang Clan",
        "song": "Clan in Da Front",
        "line": "Throw your shitty drawers in the hamper, next time, come strapped with a fuckin’ Pamper",
        "genius_link": "https://genius.com/118125"
    },
    {
        "artist": "Kanye West",
        "song": "Diamonds From Sierra Leone (Remix) ft. Jay-Z",
        "line": "This ain’t no tall order, this is nothin’ to me. Difficult takes a day, impossible takes a week",
        "genius_link": "https://genius.com/58106"
    },
    {
        "artist": "Kanye West",
        "song": "Chain Heavy ft. Talib Kweli Consequence",
        "line": "This is the makin’ of a masterpiece, so we broke out the chains and told the master, ‘Peace!’",
        "genius_link": "https://genius.com/56124"
    },
    {
        "artist": "Kanye West",
        "song": "Devil in a New Dress",
        "line": "The crib Scarface, could it be more Tony? You love me for me, could you be more phony?",
        "genius_link": "https://genius.com/78106"
    },
    {
        "artist": "Kanye West",
        "song": "Dark Fantasy",
        "line": "I fantasized ’bout this back in Chicago, mercy, mercy me, that Murciélago",
        "genius_link": "https://genius.com/366504"
    },
    {
        "artist": "Kanye West",
        "song": "Can’t Tell Me Nothing",
        "line": "Class started two hours ago, oh, am I late? No, I already graduated. And you can live through anything if Magic made it",
        "genius_link": "https://genius.com/25898"
    },
    {
        "artist": "Jay Z",
        "song": "FUTW",
        "line": "Feelin’ like a stranger in my own land, got me feeling like Brody in Homeland",
        "genius_link": "https://genius.com/1935123"
    },
    {
        "artist": "DJ Khaled",
        "song": "I Got the Keys ft. Future & Jay Z",
        "line": "My swag different, that bag different. My wife Beyoncé, I brag different.",
        "genius_link": "https://genius.com/9824905"
    },
    {
        "artist": "Jay Z",
        "song": "On To The Next One ft. Swizz Beatz",
        "line": "World can’t hold me, too much ambition. Always knew it’d be like this when I was in the kitchen",
        "genius_link": "https://genius.com/Jay-z-on-to-the-next-one-lyrics"
    },
    {
        "artist": "Lupe Fiasco",
        "song": "I’m Beamin’",
        "line": "Hood’s where the heart is, nerd’s where the words from. Don’t represent either because I merged them",
        "genius_link": "https://genius.com/23740"
    },
    {
        "artist": "Gucci Mane",
        "song": "Champions ft. Kanye West, Big Sean, 2 Chainz, Travis Scott, Yo Gotti, Quavo & Desiigner",
        "line": "I love my Auntie Jane, but fuck Uncle Sam. I’m a walkin’ money machine, check my Instagram",
        "genius_link": "https://genius.com/9270796"
    },
    {
        "artist": "Jay-Z",
        "song": "Nickles and Dimes",
        "line": "Hublot homie, two door homie. You don’t know all the shit I do for the homies",
        "genius_link": "https://genius.com/1940237"
    },
    {
        "artist": "DJ Khaled",
        "song": "I’m On One ft. Drake, Rick Ross & Lil Wayne",
        "line": "I’m a made n****, I should dust something. You n****s on the bench, like the bus coming",
        "genius_link": "https://genius.com/22428351"
    },
    {
        "artist": "Chiddy Bang",
        "song": "Nothing On We",
        "line": "Beamer, Benz, or Bentley, like Ford I got focus",
        "genius_link": "https://genius.com/185753"
    },
    {
        "artist": "Talib Kweli",
        "song": "Push Thru ft. Glen Reynolds, Kendrick Lamar & Curren$y",
        "line": "Too many daps you might receive from the things you achieve, relax. That’s what my mental say, but my physical’s been detached",
        "genius_link": "https://genius.com/Talib-kweli-push-thru-lyrics"
    },
    {
        "artist": "Clipse",
        "song": "Grindin’ ft. Pharrell Williams",
        "line": "My grind's ’bout family, never been about fame. From days I wasn’t able, there was always ’caine",
        "genius_link": "https://genius.com/58065"
    },
    {
        "artist": "Kanye West",
        "song": "We Major ft. Really Doe & Nas",
        "line": "Look, I used to cook before I had the game took. Either way, my change came like Sam Cooke",
        "genius_link": "https://genius.com/86919"
    }
]

=== thatline/thatline.github.io/docs/data/lines.json
[
    {
        "artist": "Estelle",
        "song": "American Boy ft. Kanye West",
        "line": "Look at this pea coat, tell me he’s broke",
        "genius_link": "https://genius.com/91238"
    },
    {
        "artist": "Tinie Tempah",
        "song": "Pass Out",
        "line": "Now I drive past the bus I used to run for",
        "genius_link": "https://genius.com/Tinie-tempah-pass-out-lyrics"
    },
    {
        "artist": "Kanye West",
        "song": "Junya",
        "line": "I won with the bucks, boy, let me Giannis",
        "genius_link": "https://genius.com/23571738"
    },
    {
        "artist": "The Weeknd",
        "song": "Sidewalks ft. Kendrick Lamar",
        "line": "Grew up with no father so nobody ever son me",
        "genius_link": "https://genius.com/10897433"
    },
    {
        "artist": "The Weeknd",
        "song": "Tell Your Friends",
        "line": "Cruise through the west–end in my new Benz, I’m just tryna live life through a new lens",
        "genius_link": "https://genius.com/7659455"
    },
    {
        "artist": "Lupe Fiasco",
        "song": "The Show Goes On",
        "line": "I was once that little boy, Terrified of the world, now I’m on a world tour",
        "genius_link": "https://genius.com/15947465/Lupe-fiasco-the-show-goes-on/Yeah-yeah-the-world-is-yours-i-was-once-that-little-boy-terrified-of-the-world-now-im-on-a-world-tour"
    },
    {
        "artist": "Consequence",
        "song": "Grammy Family ft. Kanye West, DJ Khaled, John Legend",
        "line": "Hi haters I’m back off hiatus, I feel just like you, I mean even I hate us",
        "genius_link": "https://genius.com/Consequence-grammy-family-lyrics"
    },
    {
        "artist": "Jay Z",
        "song": "U Don’t Know",
        "line": "Put me anywhere on God’s green earth,  I’ll triple my worth",
        "genius_link": "https://genius.com/381141"
    }
]

=== thatline/thatline.github.io/lines.json
[
    {
        "artist": "Estelle",
        "song": "American Boy ft. Kanye West",
        "line": "Look at this pea coat, tell me he's broke",
        "genius_link": "https://genius.com/91238"
    },
    {
        "artist": "Tinie Tempah",
        "song": "Pass Out",
        "line": "Now I drive past the bus I used to run for",
        "genius_link": "https://genius.com/Tinie-tempah-pass-out-lyrics"
    },
    {
        "artist": "Kanye West",
        "song": "Junya",
        "line": "I won with the bucks, boy // Let me Giannis // I won with the bucks, boy // The spirit is on us",
        "genius_link": "https://genius.com/23571738"
    },
    {
        "artist": "The Weeknd",
        "song": "Sidewalks ft. Kendrick Lamar",
        "line": "Grew up with no father so nobody ever \"son\" me",
        "genius_link": "https://genius.com/10897433"
    },
    {
        "artist": "The Weeknd",
        "song": "Tell Your Friends",
        "line": "Cruise through the westâ€“end in my new Benz // I'm just tryna live life through a new lens",
        "genius_link": "https://genius.com/7659455"
    },
    {
        "artist": "Lupe Fiasco",
        "song": "The Show Goes On",
        "line": "Yeah, yeah, the world is yours, I was once that little boy // Terrified of the world, now I'm on a world tour",
        "genius_link": "https://genius.com/15947465/Lupe-fiasco-the-show-goes-on/Yeah-yeah-the-world-is-yours-i-was-once-that-little-boy-terrified-of-the-world-now-im-on-a-world-tour"
    }
]
